### ISSUE TITLE
Queuing warehouses

### ISSUE THREAD

**Issue by EloiSanchez** [EloiSanchez/snowflake-health-check#10]
### Description

Checks for warehouses that have experienced queuing.

### Results

A table with the warehouse name and the queuing time that it experienced.

**Comment by EloiSanchez** [comment]
Two plots are requested for this health check as well:

1. Plot showing for a specific day (passed to the function), and with time granularity of 5/10/15 min (tbd) the load, queuing, provisioning... of that warehouse.
2. More general plot showing an overview of one (or several, in multiple subplots) warehouse with the same x axis as before but aggregating data for a predetermined time period. The time-period can be user determined or always give the aggregation for all time.

Think of it as a proof of concept. For now make it so the user passes a date and a warehouse name to the function in the first one and for the second one ignore making the time period user dependent, instead use an aggregation over all time.

**Comment by DLampriadis** [comment]
The second part:
 _More general plot showing an overview of one (or several, in multiple subplots) warehouse with the same x axis as before but aggregating data for a predetermined time period. The time-period can be user determined or always give the aggregation for all time._ 
, will be a separate issue since it will be shown in a different page. It will be the total averages of all warehouses. It will work as an overview for the warehouses.
